services:
    contao_faq.listener.insert_tags:
        class: Contao\FaqBundle\EventListener\InsertTagsListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }
        public: true
