services:
    contao_faq.listener.file_meta_information:
        class: Contao\FaqBundle\EventListener\FileMetaInformationListener
        arguments:
            - "@contao.framework"

    contao_faq.listener.insert_tags:
        class: Contao\FaqBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"
