services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    contao_faq.listener.insert_tags:
        class: Contao\FaqBundle\EventListener\InsertTagsListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }

    contao_faq.picker.faq_provider:
        class: Contao\FaqBundle\Picker\FaqPickerProvider
        arguments:
            - '@knp_menu.factory'
            - '@router'
            - '@?translator'
            - '@security.helper'
        tags:
            - { name: contao.picker_provider, priority: 64 }
