services:
    contao_faq.listener.faq_picker_provider:
        class: Contao\FaqBundle\Menu\FaqPickerProvider
        public: false
        arguments:
            - "@router"
            - "@security.token_storage"
            - "@request_stack"
        calls:
            - ["setFramework", ["@contao.framework"]]
        tags:
            - { name: contao.picker_menu_provider, priority: 64 }
