services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    contao_faq.listener.faq_picker_provider:
        class: Contao\FaqBundle\Menu\FaqPickerProvider
        public: false
        arguments:
            - "@router"
            - "@request_stack"
            - "@security.token_storage"
        tags:
            - { name: contao.picker_menu_provider, priority: 64 }
